name: Génération Contenu Abdias

on:
  schedule:
    # Exécute tous les jours à 8h du matin (UTC)
    # Pour 8h heure locale au Bénin (WAT = UTC+1), utiliser 7h UTC
    - cron: '0 7 * * *'
  workflow_dispatch: # Permet l'exécution manuelle pour tester

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Clean npm cache
      run: npm cache clean --force
      
    - name: Remove package-lock.json
      run: rm -f package-lock.json
      
    - name: Install dependencies
      run: |
        npm install --no-package-lock
        npm audit fix --force
      
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
        
    - name: Create .env file
      run: |
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
        echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}" >> .env
        echo "GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}" >> .env
        echo "GOOGLE_SHEETS_ID=${{ secrets.GOOGLE_SHEETS_ID }}" >> .env
        echo "POSTS_PER_DAY=5" >> .env
        
    - name: Generate content
      run: npm run generate
      
    - name: Show result
      run: |
        echo "✅ Génération de contenu terminée"
        echo "📊 Vérifiez votre Google Sheets pour les nouveaux contenus"
